@HostAddressRoot = https://localhost:45001

GET {{HostAddressRoot}}/api/destinations?searchFor=a
Accept: application/json

###
GET {{HostAddressRoot}}/api/destinations
Accept: application/json

###
GET {{HostAddressRoot}}/api/itineraries
Accept: application/json

###
GET {{HostAddressRoot}}/api/itineraries/23/stops
Accept: application/json

###
POST {{HostAddressRoot}}/api/itineraries/222/stops
Accept: application/json
Content-Type: application/json
{
  "name" : "test create stop",
  "imageUri": "https://localhost:45000/images/perelachaise.jpg",
  "itineraryId": 222
}